---
# heavily inspired by https://gist.github.com/lachesis/943769f3fac740d5848352752ac08741
- name: Create ACME.sh user
  user:
      name: '{{ acme_user }}'
      home: '{{ acme_home_dir }}'
      state: present

- name: "Pre-installation task for acme.sh: Install socat"
  apt:
    name: socat
    state: latest

- name: "Tighten permissions on ACME homedir"
  file:
    path: '{{ acme_home_dir }}'
    mode: '700'

- name: "Create ACME pki dir"
  file:
    dest: '{{ acme_pki_dir }}'
    owner: '{{ acme_pki_dir_owner }}'
    group: '{{ acme_pki_dir_group }}'
    mode: '{{ acme_pki_dir_permissions }}'
    state: directory

- name: "Create ACME well-known dir"
  file:
    dest: '{{ acme_well_known_dir }}'
    owner: '{{ acme_well_known_dir_owner }}'
    group: '{{ acme_well_known_dir_group }}'
    mode: '{{ acme_well_known_dir_permissions }}'
    state: directory

- name: "Download acme.sh from the wild GitHub"
  get_url:
    url: "{{ acme_script_url }}"
    dest: '{{ acme_script }}'
    mode: '0755'

- name: "Make acme.sh accessible in {{ acme_symlink_to_local }}"
  file:
    src: "{{ acme_script }}"
    dest: "{{ acme_symlink_to_local }}"
    state: link
  when: acme_symlink_to_local is defined

- name: "Install acme in {{ acme_install_dir }}"
  shell: "acme.sh --install --home \"{{ acme_install_dir }}\""
  args:
    chdir: "{{ acme_home_dir }}"
    creates: '{{ acme_install_dir }}/.acme.sh'
  register: acme_install_output
- debug:
      var: acme_install_output.stdout_lines